image:
  tag: "5.7.33"
auth:
  rootPassword: "test100"
  database: test100
  username: test100
  password: "test100"

metrics:
  enabled: false
  serviceMonitor:
    enabled: true

primary:
  configuration: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/plugin
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=utf8mb4
    collation-server=utf8mb4_bin
    default-storage-engine=INNODB
    max_allowed_packet=256M
    innodb_log_file_size=2GB
    transaction-isolation=READ-COMMITTED
    binlog_format=row

    [client]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/plugin

    [manager]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid


  extraEnvVars:
    - name: TZ
      value: 'Europe/Amsterdam'
    - name: Test_SSM
      value: val1
    - name: Test_SSM2
      value: val2
    - name: Test_SSM3
      value: val3

  ## Persist data to a persistent volume
  persistence:
    enabled: false


  resources:
    limits: {}
    #   memory: 256Mi
    #   cpu: 250m
    requests:
      memory: 100Mi
      cpu: 240m
