apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-test-2-ict-cicd
  namespace: argo-cd
  labels:
    cluster-name: ict-cicd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.5.8
    helm:
      valueFiles:
        - values.yaml
      externalValueFiles:
        - repoURL: https://github.com/catalinpan/argo-test-repo.git
          targetRevision: main
          valueFiles:
            - apps/argo-test-2/values.yaml
    chart: mysql
  destination:
    name: ict-cicd
    namespace: argo-test-2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
